// Ambient binding types for the Cloudflare production path.
//
// `@opennextjs/cloudflare` declares a global `CloudflareEnv` interface and
// exposes it to server code via `getCloudflareContext()`. We augment it here
// with Repo Wrapped's own bindings so a route handler gets a fully-typed `env`.
//
// The Workers runtime types referenced below (`DurableObjectNamespace`, `Ai`,
// `Fetcher`, …) are generated by `wrangler types` (the `cf-typegen` npm
// script) into `worker-configuration.d.ts`. Run it after editing wrangler.jsonc.
//
// -------------------------------------------------------------------------
// Obtaining `env` in a Next.js route handler (which another agent owns — this
// is documentation only, do NOT wire it here):
//
//   import { getCloudflareContext } from "@opennextjs/cloudflare";
//   import { wrapWithWorkspace } from "@/worker/agent";
//
//   export async function POST(req: Request) {
//     const { env } = await getCloudflareContext({ async: true });
//     const result = await wrapWithWorkspace(env as unknown as import("@/worker/agent").Env, repo, window);
//     return Response.json(result);
//   }
//
// `getCloudflareContext({ async: true })` works in any server context (including
// static routes and prerender); the sync form is fine inside the request path.
// -------------------------------------------------------------------------

import type { AgentRpc } from "./agent";

declare global {
  interface CloudflareEnv {
    /** The archaeology agent DO namespace. Typed with its callable RPC surface. */
    Agent: DurableObjectNamespace<AgentRpc>;
    /** Worker Loader binding backing the worker-shell (isolate) execution backend. */
    LOADER?: unknown;
    /** Workers AI binding for the single batched caption call (via AI Gateway). */
    AI?: Ai;
    /** AI Gateway id, matched to the gateway you create (see DEPLOY.md). */
    CF_AI_GATEWAY?: string;
    /** Caption model override; defaults to a small llama in @/lib/captions. */
    WRAP_MODEL?: string;
    /** Account id — only used by the local-dev REST caption fallback. */
    CF_ACCOUNT_ID?: string;
  }
}

export {};
